name: CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          components: clippy
      - run: cargo check
      - run: cargo clippy
      - run: RUSTDOCFLAGS='-D warnings' cargo doc --no-deps --document-private-items

  test-wasm32-unknown-unknown:
    name: Check wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@23f38cfb0c04af97a055f76acee94d5be71c7c82 # v1.0.16
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: wasm
          tools: wasm-pack

      - name: Check
        run: |
          rustup target add wasm32-unknown-unknown
          cargo check -p json-strip-comments-wasm --target wasm32-unknown-unknown

      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          package_json_file: ./wasm/package.json

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: pnpm
          cache-dependency-path: ./wasm/pnpm-lock.yaml

      - working-directory: wasm
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm run test
